import 'dotenv/config';import express from 'express';import helmet from 'helmet';import {rateLimit} from 'express-rate-limit';import jwt from 'jsonwebtoken';import {randomBytes,randomUUID,randomInt,createHash,scrypt as rawScrypt,timingSafeEqual} from 'node:crypto';import {promisify} from 'node:util';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {z} from 'zod';import {initDB,query} from './db.mjs';import {sendSmtpMail} from './smtp.mjs';
const scrypt=promisify(rawScrypt),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),app=express(),prod=process.env.NODE_ENV==='production';
let secret=process.env.JWT_SECRET;if(!secret){if(prod)throw Error('Set JWT_SECRET to at least 32 random characters.');const dir=process.env.DATA_DIR||path.join(root,'private-data');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'session-secret');if(!fs.existsSync(file))fs.writeFileSync(file,randomBytes(48).toString('hex'),{mode:0o600});secret=fs.readFileSync(file,'utf8');}if(secret.length<32)throw Error('JWT_SECRET must contain at least 32 characters.');
let firebaseAdminApp=null,firebaseAdminError='Firebase is not configured.';
async function configureFirebaseAdmin(){
  const required=['FIREBASE_PROJECT_ID','FIREBASE_CLIENT_EMAIL','FIREBASE_PRIVATE_KEY'];
  if(required.some(key=>!process.env[key])){firebaseAdminError='Firebase Admin credentials are incomplete.';return}
  try{const {getApps,initializeApp,cert}=await import('firebase-admin/app');firebaseAdminApp=getApps()[0]||initializeApp({credential:cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')}),projectId:process.env.FIREBASE_PROJECT_ID});firebaseAdminError=''}catch(error){firebaseAdminError='Firebase Admin credentials are invalid. Replace the service-account private key and restart the server.';console.error('Firebase Admin configuration failed:',error.message)}}
await initDB();await configureFirebaseAdmin();if(process.env.TRUST_PROXY==='1')app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'","https://apis.google.com"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:","blob:","https://www.themealdb.com"],connectSrc:["'self'","https://*.googleapis.com","https://*.firebaseapp.com","https://*.firebaseio.com"],frameSrc:["'self'","https://*.firebaseapp.com","https://accounts.google.com","https://www.facebook.com"],objectSrc:["'none'"]}},crossOriginEmbedderPolicy:false}));
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(['POST','PUT','DELETE','PATCH'].includes(req.method)){const origin=req.get('origin');const allowed=process.env.PUBLIC_ORIGIN||`${req.protocol}://${req.get('host')}`;if(!origin||origin!==allowed)return res.status(403).json({error:'Request origin rejected.'});}next()});
app.use(express.json({limit:'4mb'}));app.use('/api',rateLimit({windowMs:60000,limit:180,standardHeaders:'draft-8',legacyHeaders:false}));const authLimit=rateLimit({windowMs:15*60000,limit:20,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Too many sign-in attempts. Try again in 15 minutes.'}});
function cookie(req){const found=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('form_session='));return found?.slice(13)}
async function requireUser(req,res,next){try{const token=jwt.verify(cookie(req),secret,{algorithms:['HS256'],issuer:'form-fitness',audience:'form-web'});const r=await query('SELECT id,email,display_name FROM users WHERE id=$1',[token.sub]);if(!r.rows[0])throw Error();req.user=r.rows[0];next()}catch{res.status(401).json({error:'Sign in to access your saved data.'})}}
function session(res,user){const token=jwt.sign({},secret,{algorithm:'HS256',subject:user.id,issuer:'form-fitness',audience:'form-web',expiresIn:'7d'});res.cookie('form_session',token,{httpOnly:true,secure:prod,sameSite:'lax',maxAge:7*86400000,path:'/'});res.json({user:{id:user.id,email:user.email,name:user.display_name}})}
const credentials=z.object({email:z.email().max(254).transform(s=>s.toLowerCase()),password:z.string().min(10).max(128),name:z.string().trim().min(1).max(80).optional()});
const registration=credentials.extend({name:z.string().trim().min(1).max(80),phone:z.string().trim().regex(/^\+?[0-9 ()-]{7,22}$/,'Enter a valid phone number.')});
const resetRequest=z.object({email:z.email().max(254).transform(s=>s.toLowerCase())}),resetConfirm=resetRequest.extend({otp:z.string().regex(/^\d{6}$/,'Enter the six-digit code.'),password:z.string().min(10).max(128)}),otpHash=otp=>createHash('sha256').update(otp).digest('hex');
app.get('/api/health',(req,res)=>res.json({ok:true}));app.get('/api/config',(req,res)=>res.json({firebase:firebaseAdminApp&&process.env.FIREBASE_API_KEY?{enabled:true,apiKey:process.env.FIREBASE_API_KEY,authDomain:process.env.FIREBASE_AUTH_DOMAIN,projectId:process.env.FIREBASE_PROJECT_ID,appId:process.env.FIREBASE_APP_ID}:{enabled:false,reason:firebaseAdminError},barcode:true,externalRecipes:true,aiRecipes:Boolean(process.env.GEMINI_API_KEY)}));
app.post('/api/auth/register',authLimit,async(req,res)=>{const x=registration.parse(req.body);const salt=randomBytes(16).toString('hex'),hash=Buffer.from(await scrypt(x.password,salt,64)).toString('hex'),u={id:randomUUID(),email:x.email,display_name:x.name,phone:x.phone};try{await query('INSERT INTO users (id,email,password_hash,display_name,phone,created_at) VALUES ($1,$2,$3,$4,$5,$6)',[u.id,u.email,salt+':'+hash,u.display_name,u.phone,new Date().toISOString()])}catch(e){if(e.code==='23505'||String(e.message).includes('UNIQUE'))return res.status(409).json({error:'An account with this email already exists.'});throw e}session(res,u)});
app.post('/api/auth/login',authLimit,async(req,res)=>{const x=credentials.parse(req.body),r=await query('SELECT * FROM users WHERE email=$1 AND firebase_uid IS NULL',[x.email]),u=r.rows[0];const [salt,expected]=(u?.password_hash||'dummy:'+ '00'.repeat(64)).split(':');const hash=Buffer.from(await scrypt(x.password,salt,64));if(!u||!timingSafeEqual(hash,Buffer.from(expected,'hex')))return res.status(401).json({error:'Email or password is incorrect.'});session(res,u)});
app.post('/api/auth/forgot-password',authLimit,async(req,res)=>{const x=resetRequest.parse(req.body);if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS||!process.env.SMTP_FROM)return res.status(503).json({error:'Password reset email is not configured yet.'});const u=(await query('SELECT id FROM users WHERE email=$1 AND firebase_uid IS NULL',[x.email])).rows[0];if(u){const otp=String(randomInt(0,1000000)).padStart(6,'0'),expires=new Date(Date.now()+10*60000).toISOString();await query('DELETE FROM password_resets WHERE user_id=$1',[u.id]);await query('INSERT INTO password_resets (id,user_id,code_hash,expires_at,attempts,created_at) VALUES ($1,$2,$3,$4,0,$5)',[randomUUID(),u.id,otpHash(otp),expires,new Date().toISOString()]);try{await sendSmtpMail({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT)||587,secure:process.env.SMTP_SECURE==='true',user:process.env.SMTP_USER,password:process.env.SMTP_PASS.replace(/\s/g,''),from:process.env.SMTP_FROM,to:x.email,subject:'Your FORM password reset code',text:`Your FORM password reset code is: ${otp}\n\nIt expires in 10 minutes. Do not share this code with anyone.`})}catch(error){await query('DELETE FROM password_resets WHERE user_id=$1',[u.id]);console.error('Password reset email failed:',error.message);return res.status(503).json({error:'We could not send a reset email. Check the SMTP configuration and try again.'})}}res.json({message:'If an account exists for that email, a six-digit reset code has been sent.'})});
app.post('/api/auth/reset-password',authLimit,async(req,res)=>{const x=resetConfirm.parse(req.body),u=(await query('SELECT id FROM users WHERE email=$1 AND firebase_uid IS NULL',[x.email])).rows[0];if(!u)return res.status(400).json({error:'The code is invalid or expired.'});const reset=(await query('SELECT * FROM password_resets WHERE user_id=$1',[u.id])).rows[0];if(!reset||new Date(reset.expires_at).getTime()<Date.now()||Number(reset.attempts)>=5)return res.status(400).json({error:'The code is invalid or expired.'});const received=Buffer.from(otpHash(x.otp),'hex'),expected=Buffer.from(reset.code_hash,'hex');if(received.length!==expected.length||!timingSafeEqual(received,expected)){await query('UPDATE password_resets SET attempts=attempts+1 WHERE id=$1',[reset.id]);return res.status(400).json({error:'The code is invalid or expired.'})}const salt=randomBytes(16).toString('hex'),hash=Buffer.from(await scrypt(x.password,salt,64)).toString('hex');await query('UPDATE users SET password_hash=$1 WHERE id=$2',[salt+':'+hash,u.id]);await query('DELETE FROM password_resets WHERE user_id=$1',[u.id]);res.json({message:'Password updated. You can now sign in.'})});
app.post('/api/auth/firebase',authLimit,async(req,res)=>{if(!firebaseAdminApp)return res.status(503).json({error:`Google/Facebook sign-in is unavailable. ${firebaseAdminError}`});const {getAuth}=await import('firebase-admin/auth');let token;try{token=await getAuth(firebaseAdminApp).verifyIdToken(z.string().max(10000).parse(req.body.token),true)}catch{return res.status(401).json({error:'The identity token could not be verified.'})}let u=(await query('SELECT * FROM users WHERE firebase_uid=$1',[token.uid])).rows[0];if(!u){u={id:randomUUID(),email:token.email||'',display_name:token.name||'Member'};await query('INSERT INTO users (id,email,firebase_uid,display_name,created_at) VALUES ($1,$2,$3,$4,$5)',[u.id,u.email,token.uid,u.display_name,new Date().toISOString()])}session(res,u)});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('form_session',{path:'/',httpOnly:true,secure:prod,sameSite:'lax'});res.json({ok:true})});
app.get('/api/me',requireUser,(req,res)=>res.json({user:{id:req.user.id,email:req.user.email,name:req.user.display_name}}));
app.get('/api/state',requireUser,async(req,res)=>{const r=await query('SELECT document,revision FROM user_state WHERE user_id=$1',[req.user.id]);res.json(r.rows[0]?{state:JSON.parse(r.rows[0].document),revision:r.rows[0].revision}:{state:null,revision:-1})});
app.put('/api/state',requireUser,async(req,res)=>{const {state,revision}=z.object({state:z.record(z.string(),z.unknown()),revision:z.number().int().min(-1)}).parse(req.body);const doc=JSON.stringify(state);if(doc.length>3000000)return res.status(413).json({error:'Your account data is too large. Export and remove older records.'});if(revision===-1){try{await query('INSERT INTO user_state (user_id,document,revision) VALUES ($1,$2,0)',[req.user.id,doc]);return res.json({revision:0})}catch(e){if(e.code==='23505'||String(e.message).includes('UNIQUE'))return res.status(409).json({error:'Data changed in another tab. Reload before saving.'});throw e}}const r=await query('UPDATE user_state SET document=$1,revision=revision+1 WHERE user_id=$2 AND revision=$3 RETURNING revision',[doc,req.user.id,revision]);if(!r.rows.length)return res.status(409).json({error:'Data changed in another tab. Reload before saving.'});res.json({revision:r.rows[0].revision})});
app.post('/api/photos',requireUser,async(req,res)=>{const {image}=z.object({image:z.string().max(2800000)}).parse(req.body);const m=image.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m)return res.status(400).json({error:'Use a JPEG, PNG or WebP image under 2 MB.'});const bytes=Buffer.from(m[2],'base64');if(bytes.length>2000000)return res.status(413).json({error:'Image must be under 2 MB.'});const valid=m[1]==='image/jpeg'?bytes[0]===255&&bytes[1]===216:m[1]==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(!valid)return res.status(400).json({error:'Invalid image content.'});const count=(await query('SELECT COUNT(*) AS n FROM photos WHERE user_id=$1',[req.user.id])).rows[0].n;if(Number(count)>=100)return res.status(400).json({error:'Maximum 100 photos per account.'});const id=randomUUID();await query('INSERT INTO photos (id,user_id,mime,data,created_at) VALUES ($1,$2,$3,$4,$5)',[id,req.user.id,m[1],bytes,new Date().toISOString()]);res.json({id,url:'/api/photos/'+id})});
app.get('/api/photos/:id',requireUser,async(req,res)=>{const r=(await query('SELECT mime,data FROM photos WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id])).rows[0];if(!r)return res.sendStatus(404);res.type(r.mime).send(Buffer.from(r.data))});app.delete('/api/photos/:id',requireUser,async(req,res)=>{await query('DELETE FROM photos WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});
const mealDb='https://www.themealdb.com/api/json/v1/1';let mealIngredients=null;
function distance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let previous=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(a[i-1]===b[j-1]?0:1));previous=old}}return row[b.length]}
async function mealQuery(raw){const query=raw.trim().toLowerCase();if(!mealIngredients){const response=await fetch(`${mealDb}/list.php?i=list`,{signal:AbortSignal.timeout(8000)});if(response.ok)mealIngredients=(await response.json()).meals?.map(x=>x.strIngredient).filter(Boolean)||[]}const match=mealIngredients?.map(name=>({name,score:distance(query,name.toLowerCase())})).sort((a,b)=>a.score-b.score)[0];return match&&match.score<=Math.max(2,Math.floor(query.length*.3))?match.name:raw.trim()}
function mealCard(m){return{id:m.idMeal,name:m.strMeal,image:m.strMealThumb,category:m.strCategory||'',cuisine:m.strArea||'',source:'TheMealDB'}}
function mealDetail(m){const ingredients=[];for(let i=1;i<=20;i++){const name=m[`strIngredient${i}`]?.trim();if(name)ingredients.push({name,amount:m[`strMeasure${i}`]?.trim()||'As needed'})}return{...mealCard(m),ingredients,instructions:(m.strInstructions||'').split(/\r?\n|(?<=\.)\s+(?=[A-Z])/).map(x=>x.trim()).filter(Boolean),video:m.strYoutube||'',sourceUrl:m.strSource||`https://www.themealdb.com/meal/${m.idMeal}`}}
app.get('/api/recipes/external',async(req,res)=>{try{const raw=z.string().trim().min(2).max(80).parse(req.query.q),query=await mealQuery(raw);const urls=[`${mealDb}/search.php?s=${encodeURIComponent(query)}`,`${mealDb}/filter.php?i=${encodeURIComponent(query.replace(/\s+/g,'_'))}`],responses=await Promise.all(urls.map(url=>fetch(url,{signal:AbortSignal.timeout(8000)}))),payloads=await Promise.all(responses.map(r=>r.ok?r.json():{meals:[]})),seen=new Set(),recipes=[];for(const meal of payloads.flatMap(x=>x.meals||[])){if(!seen.has(meal.idMeal)){seen.add(meal.idMeal);recipes.push(mealCard(meal))}}res.json({query:raw,correctedQuery:query===raw?null:query,recipes:recipes.slice(0,24)})}catch(error){if(error instanceof z.ZodError)return res.status(400).json({error:'Enter at least two letters.'});res.status(503).json({error:'Live recipe search is temporarily unavailable.'})}});
app.get('/api/recipes/external/:id',async(req,res)=>{try{const id=z.string().regex(/^\d{1,12}$/).parse(req.params.id),response=await fetch(`${mealDb}/lookup.php?i=${id}`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error();const meal=(await response.json()).meals?.[0];if(!meal)return res.sendStatus(404);res.json({recipe:mealDetail(meal)})}catch(error){if(error instanceof z.ZodError)return res.status(400).json({error:'Invalid recipe.'});res.status(503).json({error:'Recipe details are temporarily unavailable.'})}});
app.post('/api/recipes/ai-suggestions',async(req,res)=>{if(!process.env.GEMINI_API_KEY)return res.status(503).json({error:'AI suggestions require a Gemini API key.'});try{const {query}=z.object({query:z.string().trim().min(2).max(80)}).parse(req.body),model=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite',prompt=`Suggest six concise recipe names centered on: ${query}. Return only a JSON array of strings. Do not claim nutrition or health benefits.`;const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const text=(await response.json()).candidates?.[0]?.content?.parts?.[0]?.text,suggestions=JSON.parse(text);res.json({suggestions:Array.isArray(suggestions)?suggestions.slice(0,6):[]})}catch{res.status(503).json({error:'AI recipe suggestions are temporarily unavailable.'})}});
app.post('/api/recipes/ai-fallback',async(req,res)=>{if(!process.env.GEMINI_API_KEY)return res.status(503).json({error:'AI recipes require a Gemini API key.'});try{const {query}=z.object({query:z.string().trim().min(2).max(80)}).parse(req.body),model=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite',prompt=`Create one practical home-cooking recipe for: ${query}. Return only JSON with name, description, category, cuisine, prepTime, cookTime, servings, ingredients (array of {name, amount}), and instructions (array of 4 to 7 concise steps). Do not provide nutrition, medical claims, safety claims, URLs, brands, or markdown. State reasonable quantities and make it clear this is a suggested recipe.`;const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}}),signal:AbortSignal.timeout(15000)});if(!response.ok){const detail=await response.json().catch(()=>null);throw Error(detail?.error?.message||'Gemini did not accept this request.')}const text=(await response.json()).candidates?.[0]?.content?.parts?.[0]?.text,recipe=z.object({name:z.string().trim().min(2).max(120),description:z.string().trim().max(300).optional(),category:z.string().trim().max(50).optional(),cuisine:z.string().trim().max(50).optional(),prepTime:z.string().trim().max(40).optional(),cookTime:z.string().trim().max(40).optional(),servings:z.union([z.number(),z.string()]).optional(),ingredients:z.array(z.object({name:z.string().trim().min(1).max(100),amount:z.string().trim().min(1).max(80)})).min(2).max(20),instructions:z.array(z.string().trim().min(1).max(400)).min(4).max(7)}).parse(JSON.parse(text));res.json({recipe:{...recipe,source:'Gemini AI'}})}catch(error){console.error('Gemini recipe fallback failed:',error.message);res.status(503).json({error:'AI recipe generation is temporarily unavailable. Check the server terminal for the Gemini error.'})}});
app.get('/api/barcode/:code',requireUser,async(req,res)=>{if(!/^\d{8,14}$/.test(req.params.code))return res.status(400).json({error:'Enter an 8–14 digit barcode.'});try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${req.params.code}.json?fields=product_name,nutriments,brands`,{headers:{'User-Agent':'FORMFitness/2.0 (personal nutrition logger)'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Lookup service unavailable');const result=await r.json();if(result.status!==1)return res.status(404).json({error:'Barcode not found. Use manual entry.'});const n=result.product.nutriments||{},nutrition={calories:n['energy-kcal_100g'],protein:n.proteins_100g,carbs:n.carbohydrates_100g,fat:n.fat_100g,fiber:n.fiber_100g??null,sodium:n.sodium_100g==null?null:n.sodium_100g*1000,cholesterol:null};if(['calories','protein','carbs','fat'].some(k=>nutrition[k]==null))return res.status(422).json({error:'This product has incomplete nutrition. Check its label and use manual entry.'});res.json({id:req.params.code,name:result.product.product_name||'Packaged food',nutrition,source:'Open Food Facts · community label data',servingSize:100,unit:'g'})}catch{res.status(503).json({error:'Barcode service unavailable. Use manual entry or try again.'})}});
app.get('/api/app-download',(req,res)=>res.json({available:fs.existsSync(path.join(root,'downloads','form-fitness.apk'))}));
app.get('/downloads/form-fitness.apk',(req,res)=>{const apk=path.join(root,'downloads','form-fitness.apk');if(!fs.existsSync(apk))return res.status(404).json({error:'The Android build is not published yet.'});res.type('application/vnd.android.package-archive');res.download(apk,'form-fitness.apk')});
app.use(express.static(path.join(root,'public'),{index:false,setHeaders:(res,file)=>{if(file.endsWith('sw.js'))res.set('Cache-Control','no-cache')}}));
app.use('/assets',express.static(path.join(root,'assets')));app.use('/data',express.static(path.join(root,'data')));app.use('/dist',express.static(path.join(root,'dist')));app.get('/',(req,res)=>res.sendFile(path.join(root,'index.html')));
app.use((err,req,res,next)=>{if(err instanceof z.ZodError)return res.status(400).json({error:err.issues[0]?.message||'Invalid input.'});console.error(err.message);res.status(500).json({error:'The server could not complete this request. Your unsaved changes remain on screen.'})});
const port=Number(process.env.PORT)||3000;if(!process.env.VERCEL)app.listen(port,'0.0.0.0',()=>console.log(`FORM running at http://localhost:${port}`));

export default app;
