export const ACTIVITY={Sedentary:1.2,'Lightly Active':1.375,'Moderately Active':1.55,'Very Active':1.725,'Extremely Active':1.9};
export const NUTRIENTS=['calories','protein','carbs','fat','fiber','sodium','cholesterol','calcium','iron','potassium','vitaminA','vitaminC','vitaminD'];
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export function calculate(p){let {age,weight,height,sex,activity,goal='Maintenance',offset=400,method='percent',proteinRate}=p;age=Number(age);weight=Number(weight);height=Number(height);offset=Number(offset);if(!Number.isFinite(age)||age<18||age>100||!Number.isFinite(weight)||weight<30||weight>350||!Number.isFinite(height)||height<120||height>230||!['Male','Female'].includes(sex)||!ACTIVITY[activity]||!['Bulk','Cut','Maintenance'].includes(goal)||offset<300||offset>500)throw Error('Enter valid adult measurements and an adjustment between 300 and 500 kcal.');const bmr=10*weight+6.25*height-5*age+(sex==='Male'?5:-161),tdee=bmr*ACTIVITY[activity],calories=tdee+(goal==='Bulk'?offset:goal==='Cut'?-offset:0);const split=goal==='Cut'?[.35,.45,.2]:[.3,.5,.2];const ranges=goal==='Cut'?[2.2,2.4]:goal==='Bulk'?[2.2,2.2]:[1.6,2.2];const rate=Number(proteinRate)||ranges[0];if(method==='weight'&&(rate<ranges[0]||rate>ranges[1]))throw Error(`Choose protein between ${ranges[0]} and ${ranges[1]} g/kg for this goal.`);const protein=method==='weight'?weight*rate:calories*split[0]/4,fat=calories*.2/9,carbs=(calories-protein*4-fat*9)/4;if(calories<1200||carbs<0)throw Error('This produces a very low or invalid target. Review your inputs with a qualified clinician.');return {bmr,tdee,calories,protein,carbs,fat,proteinRange:ranges.map(r=>r*weight),goals:{Bulk:tdee+400,Cut:tdee-400,Maintenance:tdee},weekly:{calories:calories*7,protein:protein*7,carbs:carbs*7,fat:fat*7}};}
export function scaleNutrition(n,factor){return Object.fromEntries(NUTRIENTS.map(k=>[k,n[k]==null?null:n[k]*factor]));}
export function totalNutrition(entries){return Object.fromEntries(NUTRIENTS.map(k=>[k,entries.length&&entries.every(n=>n[k]!=null)?entries.reduce((s,n)=>s+n[k],0):['calories','protein','carbs','fat'].includes(k)?entries.reduce((s,n)=>s+(n[k]||0),0):null]));}
export function weekDates(date){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-(d.getDay()+6)%7);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(x.getDate()+i);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`})}
export function makePlan(recipes,goal='Maintenance',target=goal==='Bulk'?2750:goal==='Cut'?2000:2250){const cats=goal==='Bulk'?['Breakfast','Snack','Lunch','Snack','Dinner','Snack']:['Breakfast','Lunch','Snack','Dinner'];return Array.from({length:7},(_,day)=>{const items=cats.map((cat,i)=>({recipeId:recipes.filter(r=>r.category===cat)[(day+i*2)%10].id,servings:1,slot:i===5?'Post-Workout':cat}));const cal=items.reduce((s,i)=>s+recipes.find(r=>r.id===i.recipeId).nutrition.calories,0);return items.map(i=>({...i,servings:Math.round(target/cal*1000)/1000}))})}
export function shoppingList(plan,recipes){const map=new Map();plan.flat().forEach(item=>{const r=recipes.find(r=>r.id===item.recipeId);if(!r)return;r.ingredients.forEach(i=>{const key=i.foodId+'|'+i.unit;const old=map.get(key)||{name:i.name,unit:i.unit,amount:0};old.amount+=i.amount*item.servings/r.servings;map.set(key,old)})});return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
export const initialState=()=>({profile:null,logs:[],workouts:[],weight:[],records:[],favorites:{exercises:[],recipes:[],supplements:[],plans:[]},plan:null,routine:[],supplementStock:[],supplementLogs:[],reviews:{},reminders:[],preferences:{theme:'dark',exerciseAdjustment:false},photos:[]});
