import React,{createContext,useContext,useEffect,useRef} from 'react';import Chart from 'chart.js/auto';
export const Context=createContext(null);export const useApp=()=>useContext(Context);export const fmt=(x,d=0)=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:d});
export async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});let d;try{d=await r.json()}catch{throw Error('The application server is not running. Start the project with npm start.')}if(!r.ok)throw Object.assign(Error(d.error||'Request failed.'),{status:r.status});return d}
export function Field({label,children,...props}){return <label className="field"><span>{label}</span>{children||<input {...props}/>}</label>}
export function Select({label,options,...props}){return <Field label={label}><select {...props}>{options.map(o=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select></Field>}
export function Modal({title,children,onClose,className=''}){const ref=useRef();useEffect(()=>{const previous=document.activeElement;const d=ref.current;d.showModal();const fn=e=>{e.preventDefault();onClose()};d.addEventListener('cancel',fn);return()=>{d.removeEventListener('cancel',fn);d.close();previous?.focus?.()}},[]);return <dialog ref={ref} className={'modal '+className} onClick={e=>{if(e.target===ref.current){const r=ref.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose()}}}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}>×</button></header>{children}</dialog>}
export function Graph({type='bar',labels,datasets,title}){const ref=useRef();useEffect(()=>{const chart=new Chart(ref.current,{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:type==='doughnut'||datasets.length>1,labels:{color:'#9ca59b'}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#97a18f'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#97a18f'},grid:{color:'#2b342b'}}}}});return()=>chart.destroy()},[type,JSON.stringify(labels),JSON.stringify(datasets)]);return <div className="chart"><canvas ref={ref} role="img" aria-label={title}>{title}</canvas></div>}
export function MacroChart({nutrition}){return <Graph title={`Macro calories: protein ${fmt(nutrition.protein*4)}, carbs ${fmt(nutrition.carbs*4)}, fat ${fmt(nutrition.fat*9)}`} type="doughnut" labels={['Protein','Carbs','Fat']} datasets={[{data:[nutrition.protein*4,nutrition.carbs*4,nutrition.fat*9],backgroundColor:['#c7f36b','#7bbfc7','#b69be6'],borderWidth:0}]}/>}
export function Nutrients({nutrition,full=false}){const names=full?['calories','protein','carbs','fat','fiber','sodium','cholesterol','calcium','iron','potassium','vitaminA','vitaminC','vitaminD']:['calories','protein','carbs','fat'];return <div className="nutrients">{names.map(k=><div key={k}><small>{k.replace('vitamin','Vitamin ')}</small><strong>{fmt(nutrition[k],k==='calories'?0:1)} <em>{k==='calories'?'kcal':['sodium','cholesterol','calcium','iron','potassium','vitaminC'].includes(k)?'mg':['vitaminA','vitaminD'].includes(k)?'µg':'g'}</em></strong></div>)}</div>}
export function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function Empty({children}){return <div className="empty-state">{children}</div>}
export function PageTitle({kicker,title,children}){return <div className="page-title"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1></div>{children}</div>}
export function Favorite({kind,id}){const {state,commit}=useApp();const has=state.favorites[kind].includes(id);return <button className={'favorite '+(has?'selected':'')} aria-label={has?'Remove favorite':'Save favorite'} aria-pressed={has} onClick={()=>commit(s=>({...s,favorites:{...s.favorites,[kind]:has?s.favorites[kind].filter(x=>x!==id):[...s.favorites[kind],id]}}))}>{has?'★':'☆'}</button>}
export function Review({id}){const {state,commit}=useApp();const review=state.reviews[id]||{rating:5,text:''};return <form className="panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);commit(s=>({...s,reviews:{...s.reviews,[id]:{rating:Number(f.get('rating')),text:f.get('text')}}}))}}><h3>Your review</h3><p className="muted">Private to your account. No public ratings have been collected.</p><Select label="Rating" name="rating" defaultValue={review.rating} options={[1,2,3,4,5].map(n=>({value:n,label:'★'.repeat(n)}))}/><Field label="Notes"><textarea name="text" defaultValue={review.text} maxLength={1000}/></Field><button className="secondary">Save review</button></form>}
